# ./.tmuxinator.yml
#
# IMPORTANT !!!
# This project is meant to be executed with sudo

name: merged-examples
root: ./

on_project_start: ./_up.sh

on_project_stop: ./_down.sh

windows:
  - Booking:
      layout: even-vertical
      panes:
        - ip netns exec ns_c iperf3 -i 2 -s -f m
        - ./with_python.py <%= @settings["drop_rate"] %> <%= @settings["limit_rate"] %> 
