# ./.tmuxinator.yml

name: nftables-rules
root: ./

startup_window: htop

windows:
  - iperf3_server:
      panes:
        - iperf3 -i 2 -s -f m
  - htop:
      layout: even-vertical
      panes:
        - iperf3 -i 2 -c localhost -u --udp-counters-64bit -b 10g --blockcount 10000000 --length 1472 -P 1
        - HTOPRC=./htoprc htop -u root
